// =================================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package admin

import (
	"context"

	"ecboot/api/admin/v1"
)

type IAdminV1 interface {
	AdminGroupBuyList(ctx context.Context, req *v1.AdminGroupBuyListReq) (res *v1.AdminGroupBuyListRes, err error)
	AdminGroupBuyCreate(ctx context.Context, req *v1.AdminGroupBuyCreateReq) (res *v1.AdminGroupBuyCreateRes, err error)
	AdminGroupBuyUpdate(ctx context.Context, req *v1.AdminGroupBuyUpdateReq) (res *v1.AdminGroupBuyUpdateRes, err error)
	AdminGroupBuyDelete(ctx context.Context, req *v1.AdminGroupBuyDeleteReq) (res *v1.AdminGroupBuyDeleteRes, err error)
	AdminGroupBuyItems(ctx context.Context, req *v1.AdminGroupBuyItemsReq) (res *v1.AdminGroupBuyItemsRes, err error)
	AdminFlashSaleList(ctx context.Context, req *v1.AdminFlashSaleListReq) (res *v1.AdminFlashSaleListRes, err error)
	AdminFlashSaleCreate(ctx context.Context, req *v1.AdminFlashSaleCreateReq) (res *v1.AdminFlashSaleCreateRes, err error)
	AdminFlashSaleUpdate(ctx context.Context, req *v1.AdminFlashSaleUpdateReq) (res *v1.AdminFlashSaleUpdateRes, err error)
	AdminFlashSaleDelete(ctx context.Context, req *v1.AdminFlashSaleDeleteReq) (res *v1.AdminFlashSaleDeleteRes, err error)
	AdminFlashSaleItems(ctx context.Context, req *v1.AdminFlashSaleItemsReq) (res *v1.AdminFlashSaleItemsRes, err error)
	AdminBargainList(ctx context.Context, req *v1.AdminBargainListReq) (res *v1.AdminBargainListRes, err error)
	AdminBargainCreate(ctx context.Context, req *v1.AdminBargainCreateReq) (res *v1.AdminBargainCreateRes, err error)
	AdminBargainUpdate(ctx context.Context, req *v1.AdminBargainUpdateReq) (res *v1.AdminBargainUpdateRes, err error)
	AdminBargainDelete(ctx context.Context, req *v1.AdminBargainDeleteReq) (res *v1.AdminBargainDeleteRes, err error)
	AdminBargainItems(ctx context.Context, req *v1.AdminBargainItemsReq) (res *v1.AdminBargainItemsRes, err error)
	AdminAssistList(ctx context.Context, req *v1.AdminAssistListReq) (res *v1.AdminAssistListRes, err error)
	AdminAssistCreate(ctx context.Context, req *v1.AdminAssistCreateReq) (res *v1.AdminAssistCreateRes, err error)
	AdminAssistUpdate(ctx context.Context, req *v1.AdminAssistUpdateReq) (res *v1.AdminAssistUpdateRes, err error)
	AdminAssistDelete(ctx context.Context, req *v1.AdminAssistDeleteReq) (res *v1.AdminAssistDeleteRes, err error)
	AdminAfterSaleList(ctx context.Context, req *v1.AdminAfterSaleListReq) (res *v1.AdminAfterSaleListRes, err error)
	AdminAfterSaleDetail(ctx context.Context, req *v1.AdminAfterSaleDetailReq) (res *v1.AdminAfterSaleDetailRes, err error)
	AdminAfterSaleApprove(ctx context.Context, req *v1.AdminAfterSaleApproveReq) (res *v1.AdminAfterSaleApproveRes, err error)
	AdminAfterSaleReject(ctx context.Context, req *v1.AdminAfterSaleRejectReq) (res *v1.AdminAfterSaleRejectRes, err error)
	AdminAfterSaleConfirmReceipt(ctx context.Context, req *v1.AdminAfterSaleConfirmReceiptReq) (res *v1.AdminAfterSaleConfirmReceiptRes, err error)
	AdminAfterSaleRetryRefund(ctx context.Context, req *v1.AdminAfterSaleRetryRefundReq) (res *v1.AdminAfterSaleRetryRefundRes, err error)
	AdminOperationLogList(ctx context.Context, req *v1.AdminOperationLogListReq) (res *v1.AdminOperationLogListRes, err error)
	AdminLoginLogList(ctx context.Context, req *v1.AdminLoginLogListReq) (res *v1.AdminLoginLogListRes, err error)
	AdminLogin(ctx context.Context, req *v1.AdminLoginReq) (res *v1.AdminLoginRes, err error)
	AdminTokenRefresh(ctx context.Context, req *v1.AdminTokenRefreshReq) (res *v1.AdminTokenRefreshRes, err error)
	AdminLogout(ctx context.Context, req *v1.AdminLogoutReq) (res *v1.AdminLogoutRes, err error)
	AdminProfile(ctx context.Context, req *v1.AdminProfileReq) (res *v1.AdminProfileRes, err error)
	AdminChangePassword(ctx context.Context, req *v1.AdminChangePasswordReq) (res *v1.AdminChangePasswordRes, err error)
	AdminConfigList(ctx context.Context, req *v1.AdminConfigListReq) (res *v1.AdminConfigListRes, err error)
	AdminConfigUpdate(ctx context.Context, req *v1.AdminConfigUpdateReq) (res *v1.AdminConfigUpdateRes, err error)
	AdminDashboardTrade(ctx context.Context, req *v1.AdminDashboardTradeReq) (res *v1.AdminDashboardTradeRes, err error)
	AdminDashboardMember(ctx context.Context, req *v1.AdminDashboardMemberReq) (res *v1.AdminDashboardMemberRes, err error)
	AdminDashboardProduct(ctx context.Context, req *v1.AdminDashboardProductReq) (res *v1.AdminDashboardProductRes, err error)
	AdminDistributorList(ctx context.Context, req *v1.AdminDistributorListReq) (res *v1.AdminDistributorListRes, err error)
	AdminDistributorAudit(ctx context.Context, req *v1.AdminDistributorAuditReq) (res *v1.AdminDistributorAuditRes, err error)
	AdminDistributorFreeze(ctx context.Context, req *v1.AdminDistributorFreezeReq) (res *v1.AdminDistributorFreezeRes, err error)
	AdminDistRuleList(ctx context.Context, req *v1.AdminDistRuleListReq) (res *v1.AdminDistRuleListRes, err error)
	AdminDistRuleCreate(ctx context.Context, req *v1.AdminDistRuleCreateReq) (res *v1.AdminDistRuleCreateRes, err error)
	AdminDistRuleUpdate(ctx context.Context, req *v1.AdminDistRuleUpdateReq) (res *v1.AdminDistRuleUpdateRes, err error)
	AdminDistRuleDelete(ctx context.Context, req *v1.AdminDistRuleDeleteReq) (res *v1.AdminDistRuleDeleteRes, err error)
	AdminDistRecordList(ctx context.Context, req *v1.AdminDistRecordListReq) (res *v1.AdminDistRecordListRes, err error)
	AdminWithdrawList(ctx context.Context, req *v1.AdminWithdrawListReq) (res *v1.AdminWithdrawListRes, err error)
	AdminWithdrawAudit(ctx context.Context, req *v1.AdminWithdrawAuditReq) (res *v1.AdminWithdrawAuditRes, err error)
	AdminWithdrawPay(ctx context.Context, req *v1.AdminWithdrawPayReq) (res *v1.AdminWithdrawPayRes, err error)
	AdminInviteRecordList(ctx context.Context, req *v1.AdminInviteRecordListReq) (res *v1.AdminInviteRecordListRes, err error)
	AdminInventoryList(ctx context.Context, req *v1.AdminInventoryListReq) (res *v1.AdminInventoryListRes, err error)
	AdminInventoryAdjust(ctx context.Context, req *v1.AdminInventoryAdjustReq) (res *v1.AdminInventoryAdjustRes, err error)
	AdminInventoryWarn(ctx context.Context, req *v1.AdminInventoryWarnReq) (res *v1.AdminInventoryWarnRes, err error)
	AdminLogisticsList(ctx context.Context, req *v1.AdminLogisticsListReq) (res *v1.AdminLogisticsListRes, err error)
	AdminLogisticsCreate(ctx context.Context, req *v1.AdminLogisticsCreateReq) (res *v1.AdminLogisticsCreateRes, err error)
	AdminLogisticsUpdate(ctx context.Context, req *v1.AdminLogisticsUpdateReq) (res *v1.AdminLogisticsUpdateRes, err error)
	AdminLogisticsDelete(ctx context.Context, req *v1.AdminLogisticsDeleteReq) (res *v1.AdminLogisticsDeleteRes, err error)
	AdminLogisticsDetail(ctx context.Context, req *v1.AdminLogisticsDetailReq) (res *v1.AdminLogisticsDetailRes, err error)
	AdminMemberList(ctx context.Context, req *v1.AdminMemberListReq) (res *v1.AdminMemberListRes, err error)
	AdminMemberDetail(ctx context.Context, req *v1.AdminMemberDetailReq) (res *v1.AdminMemberDetailRes, err error)
	AdminMemberDisable(ctx context.Context, req *v1.AdminMemberDisableReq) (res *v1.AdminMemberDisableRes, err error)
	AdminMemberRebindPhone(ctx context.Context, req *v1.AdminMemberRebindPhoneReq) (res *v1.AdminMemberRebindPhoneRes, err error)
	AdminBannerList(ctx context.Context, req *v1.AdminBannerListReq) (res *v1.AdminBannerListRes, err error)
	AdminBannerCreate(ctx context.Context, req *v1.AdminBannerCreateReq) (res *v1.AdminBannerCreateRes, err error)
	AdminBannerUpdate(ctx context.Context, req *v1.AdminBannerUpdateReq) (res *v1.AdminBannerUpdateRes, err error)
	AdminBannerDelete(ctx context.Context, req *v1.AdminBannerDeleteReq) (res *v1.AdminBannerDeleteRes, err error)
	AdminFloorList(ctx context.Context, req *v1.AdminFloorListReq) (res *v1.AdminFloorListRes, err error)
	AdminFloorCreate(ctx context.Context, req *v1.AdminFloorCreateReq) (res *v1.AdminFloorCreateRes, err error)
	AdminFloorUpdate(ctx context.Context, req *v1.AdminFloorUpdateReq) (res *v1.AdminFloorUpdateRes, err error)
	AdminFloorDelete(ctx context.Context, req *v1.AdminFloorDeleteReq) (res *v1.AdminFloorDeleteRes, err error)
	AdminOrderList(ctx context.Context, req *v1.AdminOrderListReq) (res *v1.AdminOrderListRes, err error)
	AdminOrderDetail(ctx context.Context, req *v1.AdminOrderDetailReq) (res *v1.AdminOrderDetailRes, err error)
	AdminOrderDeliver(ctx context.Context, req *v1.AdminOrderDeliverReq) (res *v1.AdminOrderDeliverRes, err error)
	AdminOrderCancel(ctx context.Context, req *v1.AdminOrderCancelReq) (res *v1.AdminOrderCancelRes, err error)
	AdminOrderRemark(ctx context.Context, req *v1.AdminOrderRemarkReq) (res *v1.AdminOrderRemarkRes, err error)
	AdminCategoryTree(ctx context.Context, req *v1.AdminCategoryTreeReq) (res *v1.AdminCategoryTreeRes, err error)
	AdminCategoryCreate(ctx context.Context, req *v1.AdminCategoryCreateReq) (res *v1.AdminCategoryCreateRes, err error)
	AdminCategoryUpdate(ctx context.Context, req *v1.AdminCategoryUpdateReq) (res *v1.AdminCategoryUpdateRes, err error)
	AdminCategoryDelete(ctx context.Context, req *v1.AdminCategoryDeleteReq) (res *v1.AdminCategoryDeleteRes, err error)
	AdminBrandList(ctx context.Context, req *v1.AdminBrandListReq) (res *v1.AdminBrandListRes, err error)
	AdminBrandCreate(ctx context.Context, req *v1.AdminBrandCreateReq) (res *v1.AdminBrandCreateRes, err error)
	AdminBrandUpdate(ctx context.Context, req *v1.AdminBrandUpdateReq) (res *v1.AdminBrandUpdateRes, err error)
	AdminBrandDelete(ctx context.Context, req *v1.AdminBrandDeleteReq) (res *v1.AdminBrandDeleteRes, err error)
	AdminSpuList(ctx context.Context, req *v1.AdminSpuListReq) (res *v1.AdminSpuListRes, err error)
	AdminSpuCreate(ctx context.Context, req *v1.AdminSpuCreateReq) (res *v1.AdminSpuCreateRes, err error)
	AdminSpuDetail(ctx context.Context, req *v1.AdminSpuDetailReq) (res *v1.AdminSpuDetailRes, err error)
	AdminSpuUpdate(ctx context.Context, req *v1.AdminSpuUpdateReq) (res *v1.AdminSpuUpdateRes, err error)
	AdminSpuDelete(ctx context.Context, req *v1.AdminSpuDeleteReq) (res *v1.AdminSpuDeleteRes, err error)
	AdminSpuStatus(ctx context.Context, req *v1.AdminSpuStatusReq) (res *v1.AdminSpuStatusRes, err error)
	AdminSpuRestrict(ctx context.Context, req *v1.AdminSpuRestrictReq) (res *v1.AdminSpuRestrictRes, err error)
	AdminSkuCreate(ctx context.Context, req *v1.AdminSkuCreateReq) (res *v1.AdminSkuCreateRes, err error)
	AdminSkuUpdate(ctx context.Context, req *v1.AdminSkuUpdateReq) (res *v1.AdminSkuUpdateRes, err error)
	AdminSkuDelete(ctx context.Context, req *v1.AdminSkuDeleteReq) (res *v1.AdminSkuDeleteRes, err error)
	AdminSkuStatus(ctx context.Context, req *v1.AdminSkuStatusReq) (res *v1.AdminSkuStatusRes, err error)
	AdminCouponList(ctx context.Context, req *v1.AdminCouponListReq) (res *v1.AdminCouponListRes, err error)
	AdminCouponCreate(ctx context.Context, req *v1.AdminCouponCreateReq) (res *v1.AdminCouponCreateRes, err error)
	AdminCouponUpdate(ctx context.Context, req *v1.AdminCouponUpdateReq) (res *v1.AdminCouponUpdateRes, err error)
	AdminCouponDelete(ctx context.Context, req *v1.AdminCouponDeleteReq) (res *v1.AdminCouponDeleteRes, err error)
	AdminCouponRecordList(ctx context.Context, req *v1.AdminCouponRecordListReq) (res *v1.AdminCouponRecordListRes, err error)
	AdminFullReductionList(ctx context.Context, req *v1.AdminFullReductionListReq) (res *v1.AdminFullReductionListRes, err error)
	AdminFullReductionCreate(ctx context.Context, req *v1.AdminFullReductionCreateReq) (res *v1.AdminFullReductionCreateRes, err error)
	AdminFullReductionDetail(ctx context.Context, req *v1.AdminFullReductionDetailReq) (res *v1.AdminFullReductionDetailRes, err error)
	AdminFullReductionUpdate(ctx context.Context, req *v1.AdminFullReductionUpdateReq) (res *v1.AdminFullReductionUpdateRes, err error)
	AdminFullReductionDelete(ctx context.Context, req *v1.AdminFullReductionDeleteReq) (res *v1.AdminFullReductionDeleteRes, err error)
	AdminCouponDetail(ctx context.Context, req *v1.AdminCouponDetailReq) (res *v1.AdminCouponDetailRes, err error)
	AdminRoleList(ctx context.Context, req *v1.AdminRoleListReq) (res *v1.AdminRoleListRes, err error)
	AdminRoleCreate(ctx context.Context, req *v1.AdminRoleCreateReq) (res *v1.AdminRoleCreateRes, err error)
	AdminRoleUpdate(ctx context.Context, req *v1.AdminRoleUpdateReq) (res *v1.AdminRoleUpdateRes, err error)
	AdminRoleDelete(ctx context.Context, req *v1.AdminRoleDeleteReq) (res *v1.AdminRoleDeleteRes, err error)
	AdminPermissionTree(ctx context.Context, req *v1.AdminPermissionTreeReq) (res *v1.AdminPermissionTreeRes, err error)
	AdminRoleAssignPerm(ctx context.Context, req *v1.AdminRoleAssignPermReq) (res *v1.AdminRoleAssignPermRes, err error)
	AdminUserList(ctx context.Context, req *v1.AdminUserListReq) (res *v1.AdminUserListRes, err error)
	AdminUserCreate(ctx context.Context, req *v1.AdminUserCreateReq) (res *v1.AdminUserCreateRes, err error)
	AdminUserUpdate(ctx context.Context, req *v1.AdminUserUpdateReq) (res *v1.AdminUserUpdateRes, err error)
	AdminUserDelete(ctx context.Context, req *v1.AdminUserDeleteReq) (res *v1.AdminUserDeleteRes, err error)
	AdminUserAssignRoles(ctx context.Context, req *v1.AdminUserAssignRolesReq) (res *v1.AdminUserAssignRolesRes, err error)
	AdminRoleDetail(ctx context.Context, req *v1.AdminRoleDetailReq) (res *v1.AdminRoleDetailRes, err error)
	AdminUserDetail(ctx context.Context, req *v1.AdminUserDetailReq) (res *v1.AdminUserDetailRes, err error)
	AdminRiskRuleList(ctx context.Context, req *v1.AdminRiskRuleListReq) (res *v1.AdminRiskRuleListRes, err error)
	AdminRiskRuleCreate(ctx context.Context, req *v1.AdminRiskRuleCreateReq) (res *v1.AdminRiskRuleCreateRes, err error)
	AdminRiskRuleUpdate(ctx context.Context, req *v1.AdminRiskRuleUpdateReq) (res *v1.AdminRiskRuleUpdateRes, err error)
	AdminRiskRuleDelete(ctx context.Context, req *v1.AdminRiskRuleDeleteReq) (res *v1.AdminRiskRuleDeleteRes, err error)
	AdminRiskRecordList(ctx context.Context, req *v1.AdminRiskRecordListReq) (res *v1.AdminRiskRecordListRes, err error)
	AdminRiskAppeal(ctx context.Context, req *v1.AdminRiskAppealReq) (res *v1.AdminRiskAppealRes, err error)
	AdminRiskRuleDetail(ctx context.Context, req *v1.AdminRiskRuleDetailReq) (res *v1.AdminRiskRuleDetailRes, err error)
	AdminStoreList(ctx context.Context, req *v1.AdminStoreListReq) (res *v1.AdminStoreListRes, err error)
	AdminStoreCreate(ctx context.Context, req *v1.AdminStoreCreateReq) (res *v1.AdminStoreCreateRes, err error)
	AdminStoreUpdate(ctx context.Context, req *v1.AdminStoreUpdateReq) (res *v1.AdminStoreUpdateRes, err error)
	AdminStoreDelete(ctx context.Context, req *v1.AdminStoreDeleteReq) (res *v1.AdminStoreDeleteRes, err error)
	AdminStoreDetail(ctx context.Context, req *v1.AdminStoreDetailReq) (res *v1.AdminStoreDetailRes, err error)
}
