// =================================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package admin

import (
	"context"

	"ecboot/api/admin/v1"
)

type IAdminV1 interface {
	AdminAfterSaleList(ctx context.Context, req *v1.AdminAfterSaleListReq) (res *v1.AdminAfterSaleListRes, err error)
	AdminAfterSaleDetail(ctx context.Context, req *v1.AdminAfterSaleDetailReq) (res *v1.AdminAfterSaleDetailRes, err error)
	AdminAfterSaleApprove(ctx context.Context, req *v1.AdminAfterSaleApproveReq) (res *v1.AdminAfterSaleApproveRes, err error)
	AdminAfterSaleReject(ctx context.Context, req *v1.AdminAfterSaleRejectReq) (res *v1.AdminAfterSaleRejectRes, err error)
	AdminAfterSaleConfirmReceipt(ctx context.Context, req *v1.AdminAfterSaleConfirmReceiptReq) (res *v1.AdminAfterSaleConfirmReceiptRes, err error)
	AdminAfterSaleRetryRefund(ctx context.Context, req *v1.AdminAfterSaleRetryRefundReq) (res *v1.AdminAfterSaleRetryRefundRes, err error)
	AdminOperationLogList(ctx context.Context, req *v1.AdminOperationLogListReq) (res *v1.AdminOperationLogListRes, err error)
	AdminLoginLogList(ctx context.Context, req *v1.AdminLoginLogListReq) (res *v1.AdminLoginLogListRes, err error)
	AdminLogin(ctx context.Context, req *v1.AdminLoginReq) (res *v1.AdminLoginRes, err error)
	AdminTokenRefresh(ctx context.Context, req *v1.AdminTokenRefreshReq) (res *v1.AdminTokenRefreshRes, err error)
	AdminLogout(ctx context.Context, req *v1.AdminLogoutReq) (res *v1.AdminLogoutRes, err error)
	AdminProfile(ctx context.Context, req *v1.AdminProfileReq) (res *v1.AdminProfileRes, err error)
	AdminChangePassword(ctx context.Context, req *v1.AdminChangePasswordReq) (res *v1.AdminChangePasswordRes, err error)
	AdminConfigList(ctx context.Context, req *v1.AdminConfigListReq) (res *v1.AdminConfigListRes, err error)
	AdminConfigUpdate(ctx context.Context, req *v1.AdminConfigUpdateReq) (res *v1.AdminConfigUpdateRes, err error)
	AdminDashboardTrade(ctx context.Context, req *v1.AdminDashboardTradeReq) (res *v1.AdminDashboardTradeRes, err error)
	AdminDashboardMember(ctx context.Context, req *v1.AdminDashboardMemberReq) (res *v1.AdminDashboardMemberRes, err error)
	AdminDashboardProduct(ctx context.Context, req *v1.AdminDashboardProductReq) (res *v1.AdminDashboardProductRes, err error)
	AdminInventoryList(ctx context.Context, req *v1.AdminInventoryListReq) (res *v1.AdminInventoryListRes, err error)
	AdminInventoryAdjust(ctx context.Context, req *v1.AdminInventoryAdjustReq) (res *v1.AdminInventoryAdjustRes, err error)
	AdminInventoryWarn(ctx context.Context, req *v1.AdminInventoryWarnReq) (res *v1.AdminInventoryWarnRes, err error)
	AdminOrderList(ctx context.Context, req *v1.AdminOrderListReq) (res *v1.AdminOrderListRes, err error)
	AdminOrderDetail(ctx context.Context, req *v1.AdminOrderDetailReq) (res *v1.AdminOrderDetailRes, err error)
	AdminOrderDeliver(ctx context.Context, req *v1.AdminOrderDeliverReq) (res *v1.AdminOrderDeliverRes, err error)
	AdminOrderCancel(ctx context.Context, req *v1.AdminOrderCancelReq) (res *v1.AdminOrderCancelRes, err error)
	AdminOrderRemark(ctx context.Context, req *v1.AdminOrderRemarkReq) (res *v1.AdminOrderRemarkRes, err error)
	AdminCategoryTree(ctx context.Context, req *v1.AdminCategoryTreeReq) (res *v1.AdminCategoryTreeRes, err error)
	AdminCategoryCreate(ctx context.Context, req *v1.AdminCategoryCreateReq) (res *v1.AdminCategoryCreateRes, err error)
	AdminCategoryUpdate(ctx context.Context, req *v1.AdminCategoryUpdateReq) (res *v1.AdminCategoryUpdateRes, err error)
	AdminCategoryDelete(ctx context.Context, req *v1.AdminCategoryDeleteReq) (res *v1.AdminCategoryDeleteRes, err error)
	AdminBrandList(ctx context.Context, req *v1.AdminBrandListReq) (res *v1.AdminBrandListRes, err error)
	AdminBrandCreate(ctx context.Context, req *v1.AdminBrandCreateReq) (res *v1.AdminBrandCreateRes, err error)
	AdminBrandUpdate(ctx context.Context, req *v1.AdminBrandUpdateReq) (res *v1.AdminBrandUpdateRes, err error)
	AdminBrandDelete(ctx context.Context, req *v1.AdminBrandDeleteReq) (res *v1.AdminBrandDeleteRes, err error)
	AdminSpuList(ctx context.Context, req *v1.AdminSpuListReq) (res *v1.AdminSpuListRes, err error)
	AdminSpuCreate(ctx context.Context, req *v1.AdminSpuCreateReq) (res *v1.AdminSpuCreateRes, err error)
	AdminSpuDetail(ctx context.Context, req *v1.AdminSpuDetailReq) (res *v1.AdminSpuDetailRes, err error)
	AdminSpuUpdate(ctx context.Context, req *v1.AdminSpuUpdateReq) (res *v1.AdminSpuUpdateRes, err error)
	AdminSpuDelete(ctx context.Context, req *v1.AdminSpuDeleteReq) (res *v1.AdminSpuDeleteRes, err error)
	AdminSpuStatus(ctx context.Context, req *v1.AdminSpuStatusReq) (res *v1.AdminSpuStatusRes, err error)
	AdminSpuRestrict(ctx context.Context, req *v1.AdminSpuRestrictReq) (res *v1.AdminSpuRestrictRes, err error)
	AdminSkuCreate(ctx context.Context, req *v1.AdminSkuCreateReq) (res *v1.AdminSkuCreateRes, err error)
	AdminSkuUpdate(ctx context.Context, req *v1.AdminSkuUpdateReq) (res *v1.AdminSkuUpdateRes, err error)
	AdminSkuDelete(ctx context.Context, req *v1.AdminSkuDeleteReq) (res *v1.AdminSkuDeleteRes, err error)
	AdminSkuStatus(ctx context.Context, req *v1.AdminSkuStatusReq) (res *v1.AdminSkuStatusRes, err error)
	AdminRoleList(ctx context.Context, req *v1.AdminRoleListReq) (res *v1.AdminRoleListRes, err error)
	AdminRoleCreate(ctx context.Context, req *v1.AdminRoleCreateReq) (res *v1.AdminRoleCreateRes, err error)
	AdminRoleUpdate(ctx context.Context, req *v1.AdminRoleUpdateReq) (res *v1.AdminRoleUpdateRes, err error)
	AdminRoleDelete(ctx context.Context, req *v1.AdminRoleDeleteReq) (res *v1.AdminRoleDeleteRes, err error)
	AdminPermissionTree(ctx context.Context, req *v1.AdminPermissionTreeReq) (res *v1.AdminPermissionTreeRes, err error)
	AdminRoleAssignPerm(ctx context.Context, req *v1.AdminRoleAssignPermReq) (res *v1.AdminRoleAssignPermRes, err error)
	AdminUserList(ctx context.Context, req *v1.AdminUserListReq) (res *v1.AdminUserListRes, err error)
	AdminUserCreate(ctx context.Context, req *v1.AdminUserCreateReq) (res *v1.AdminUserCreateRes, err error)
	AdminUserUpdate(ctx context.Context, req *v1.AdminUserUpdateReq) (res *v1.AdminUserUpdateRes, err error)
	AdminUserDelete(ctx context.Context, req *v1.AdminUserDeleteReq) (res *v1.AdminUserDeleteRes, err error)
	AdminUserAssignRoles(ctx context.Context, req *v1.AdminUserAssignRolesReq) (res *v1.AdminUserAssignRolesRes, err error)
	AdminRiskRuleList(ctx context.Context, req *v1.AdminRiskRuleListReq) (res *v1.AdminRiskRuleListRes, err error)
	AdminRiskRuleCreate(ctx context.Context, req *v1.AdminRiskRuleCreateReq) (res *v1.AdminRiskRuleCreateRes, err error)
	AdminRiskRuleUpdate(ctx context.Context, req *v1.AdminRiskRuleUpdateReq) (res *v1.AdminRiskRuleUpdateRes, err error)
	AdminRiskRuleDelete(ctx context.Context, req *v1.AdminRiskRuleDeleteReq) (res *v1.AdminRiskRuleDeleteRes, err error)
	AdminRiskRecordList(ctx context.Context, req *v1.AdminRiskRecordListReq) (res *v1.AdminRiskRecordListRes, err error)
	AdminRiskAppeal(ctx context.Context, req *v1.AdminRiskAppealReq) (res *v1.AdminRiskAppealRes, err error)
}
