// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// accountLogDao is the data access object for the table account_log.
// You can define custom methods on it to extend its functionality as needed.
type accountLogDao struct {
	*internal.AccountLogDao
}

var (
	// AccountLog is a globally accessible object for table account_log operations.
	AccountLog = accountLogDao{internal.NewAccountLogDao()}
)

// Add your custom methods and functionality below.
