// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// adminOperationLogDao is the data access object for the table admin_operation_log.
// You can define custom methods on it to extend its functionality as needed.
type adminOperationLogDao struct {
	*internal.AdminOperationLogDao
}

var (
	// AdminOperationLog is a globally accessible object for table admin_operation_log operations.
	AdminOperationLog = adminOperationLogDao{internal.NewAdminOperationLogDao()}
)

// Add your custom methods and functionality below.
