// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// adminUserRoleDao is the data access object for the table admin_user_role.
// You can define custom methods on it to extend its functionality as needed.
type adminUserRoleDao struct {
	*internal.AdminUserRoleDao
}

var (
	// AdminUserRole is a globally accessible object for table admin_user_role operations.
	AdminUserRole = adminUserRoleDao{internal.NewAdminUserRoleDao()}
)

// Add your custom methods and functionality below.
