// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// afterSaleOrderDao is the data access object for the table after_sale_order.
// You can define custom methods on it to extend its functionality as needed.
type afterSaleOrderDao struct {
	*internal.AfterSaleOrderDao
}

var (
	// AfterSaleOrder is a globally accessible object for table after_sale_order operations.
	AfterSaleOrder = afterSaleOrderDao{internal.NewAfterSaleOrderDao()}
)

// Add your custom methods and functionality below.
