// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// assistHelperDao is the data access object for the table assist_helper.
// You can define custom methods on it to extend its functionality as needed.
type assistHelperDao struct {
	*internal.AssistHelperDao
}

var (
	// AssistHelper is a globally accessible object for table assist_helper operations.
	AssistHelper = assistHelperDao{internal.NewAssistHelperDao()}
)

// Add your custom methods and functionality below.
