// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// assistRecordDao is the data access object for the table assist_record.
// You can define custom methods on it to extend its functionality as needed.
type assistRecordDao struct {
	*internal.AssistRecordDao
}

var (
	// AssistRecord is a globally accessible object for table assist_record operations.
	AssistRecord = assistRecordDao{internal.NewAssistRecordDao()}
)

// Add your custom methods and functionality below.
