// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// assistActivityDao is the data access object for the table assist_activity.
// You can define custom methods on it to extend its functionality as needed.
type assistActivityDao struct {
	*internal.AssistActivityDao
}

var (
	// AssistActivity is a globally accessible object for table assist_activity operations.
	AssistActivity = assistActivityDao{internal.NewAssistActivityDao()}
)

// Add your custom methods and functionality below.
