// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// bargainActivityDao is the data access object for the table bargain_activity.
// You can define custom methods on it to extend its functionality as needed.
type bargainActivityDao struct {
	*internal.BargainActivityDao
}

var (
	// BargainActivity is a globally accessible object for table bargain_activity operations.
	BargainActivity = bargainActivityDao{internal.NewBargainActivityDao()}
)

// Add your custom methods and functionality below.
