// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// bargainItemDao is the data access object for the table bargain_item.
// You can define custom methods on it to extend its functionality as needed.
type bargainItemDao struct {
	*internal.BargainItemDao
}

var (
	// BargainItem is a globally accessible object for table bargain_item operations.
	BargainItem = bargainItemDao{internal.NewBargainItemDao()}
)

// Add your custom methods and functionality below.
