// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// bargainHelperDao is the data access object for the table bargain_helper.
// You can define custom methods on it to extend its functionality as needed.
type bargainHelperDao struct {
	*internal.BargainHelperDao
}

var (
	// BargainHelper is a globally accessible object for table bargain_helper operations.
	BargainHelper = bargainHelperDao{internal.NewBargainHelperDao()}
)

// Add your custom methods and functionality below.
