// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// bargainRecordDao is the data access object for the table bargain_record.
// You can define custom methods on it to extend its functionality as needed.
type bargainRecordDao struct {
	*internal.BargainRecordDao
}

var (
	// BargainRecord is a globally accessible object for table bargain_record operations.
	BargainRecord = bargainRecordDao{internal.NewBargainRecordDao()}
)

// Add your custom methods and functionality below.
