// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// cartItemDao is the data access object for the table cart_item.
// You can define custom methods on it to extend its functionality as needed.
type cartItemDao struct {
	*internal.CartItemDao
}

var (
	// CartItem is a globally accessible object for table cart_item operations.
	CartItem = cartItemDao{internal.NewCartItemDao()}
)

// Add your custom methods and functionality below.
