// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// commissionRuleDao is the data access object for the table commission_rule.
// You can define custom methods on it to extend its functionality as needed.
type commissionRuleDao struct {
	*internal.CommissionRuleDao
}

var (
	// CommissionRule is a globally accessible object for table commission_rule operations.
	CommissionRule = commissionRuleDao{internal.NewCommissionRuleDao()}
)

// Add your custom methods and functionality below.
