// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// commissionRecordDao is the data access object for the table commission_record.
// You can define custom methods on it to extend its functionality as needed.
type commissionRecordDao struct {
	*internal.CommissionRecordDao
}

var (
	// CommissionRecord is a globally accessible object for table commission_record operations.
	CommissionRecord = commissionRecordDao{internal.NewCommissionRecordDao()}
)

// Add your custom methods and functionality below.
