// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// couponDao is the data access object for the table coupon.
// You can define custom methods on it to extend its functionality as needed.
type couponDao struct {
	*internal.CouponDao
}

var (
	// Coupon is a globally accessible object for table coupon operations.
	Coupon = couponDao{internal.NewCouponDao()}
)

// Add your custom methods and functionality below.
