// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// distributionUserDao is the data access object for the table distribution_user.
// You can define custom methods on it to extend its functionality as needed.
type distributionUserDao struct {
	*internal.DistributionUserDao
}

var (
	// DistributionUser is a globally accessible object for table distribution_user operations.
	DistributionUser = distributionUserDao{internal.NewDistributionUserDao()}
)

// Add your custom methods and functionality below.
