// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// flashSaleActivityDao is the data access object for the table flash_sale_activity.
// You can define custom methods on it to extend its functionality as needed.
type flashSaleActivityDao struct {
	*internal.FlashSaleActivityDao
}

var (
	// FlashSaleActivity is a globally accessible object for table flash_sale_activity operations.
	FlashSaleActivity = flashSaleActivityDao{internal.NewFlashSaleActivityDao()}
)

// Add your custom methods and functionality below.
