// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// flashSaleItemDao is the data access object for the table flash_sale_item.
// You can define custom methods on it to extend its functionality as needed.
type flashSaleItemDao struct {
	*internal.FlashSaleItemDao
}

var (
	// FlashSaleItem is a globally accessible object for table flash_sale_item operations.
	FlashSaleItem = flashSaleItemDao{internal.NewFlashSaleItemDao()}
)

// Add your custom methods and functionality below.
