// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// freightRuleDao is the data access object for the table freight_rule.
// You can define custom methods on it to extend its functionality as needed.
type freightRuleDao struct {
	*internal.FreightRuleDao
}

var (
	// FreightRule is a globally accessible object for table freight_rule operations.
	FreightRule = freightRuleDao{internal.NewFreightRuleDao()}
)

// Add your custom methods and functionality below.
