// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// freightTemplateDao is the data access object for the table freight_template.
// You can define custom methods on it to extend its functionality as needed.
type freightTemplateDao struct {
	*internal.FreightTemplateDao
}

var (
	// FreightTemplate is a globally accessible object for table freight_template operations.
	FreightTemplate = freightTemplateDao{internal.NewFreightTemplateDao()}
)

// Add your custom methods and functionality below.
