// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// groupBuyItemDao is the data access object for the table group_buy_item.
// You can define custom methods on it to extend its functionality as needed.
type groupBuyItemDao struct {
	*internal.GroupBuyItemDao
}

var (
	// GroupBuyItem is a globally accessible object for table group_buy_item operations.
	GroupBuyItem = groupBuyItemDao{internal.NewGroupBuyItemDao()}
)

// Add your custom methods and functionality below.
