// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// groupBuyTeamDao is the data access object for the table group_buy_team.
// You can define custom methods on it to extend its functionality as needed.
type groupBuyTeamDao struct {
	*internal.GroupBuyTeamDao
}

var (
	// GroupBuyTeam is a globally accessible object for table group_buy_team operations.
	GroupBuyTeam = groupBuyTeamDao{internal.NewGroupBuyTeamDao()}
)

// Add your custom methods and functionality below.
