// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// groupBuyTeamMemberDao is the data access object for the table group_buy_team_member.
// You can define custom methods on it to extend its functionality as needed.
type groupBuyTeamMemberDao struct {
	*internal.GroupBuyTeamMemberDao
}

var (
	// GroupBuyTeamMember is a globally accessible object for table group_buy_team_member operations.
	GroupBuyTeamMember = groupBuyTeamMemberDao{internal.NewGroupBuyTeamMemberDao()}
)

// Add your custom methods and functionality below.
