// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// groupBuyActivityDao is the data access object for the table group_buy_activity.
// You can define custom methods on it to extend its functionality as needed.
type groupBuyActivityDao struct {
	*internal.GroupBuyActivityDao
}

var (
	// GroupBuyActivity is a globally accessible object for table group_buy_activity operations.
	GroupBuyActivity = groupBuyActivityDao{internal.NewGroupBuyActivityDao()}
)

// Add your custom methods and functionality below.
