// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// inventoryDao is the data access object for the table inventory.
// You can define custom methods on it to extend its functionality as needed.
type inventoryDao struct {
	*internal.InventoryDao
}

var (
	// Inventory is a globally accessible object for table inventory operations.
	Inventory = inventoryDao{internal.NewInventoryDao()}
)

// Add your custom methods and functionality below.
