// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// inventoryLogDao is the data access object for the table inventory_log.
// You can define custom methods on it to extend its functionality as needed.
type inventoryLogDao struct {
	*internal.InventoryLogDao
}

var (
	// InventoryLog is a globally accessible object for table inventory_log operations.
	InventoryLog = inventoryLogDao{internal.NewInventoryLogDao()}
)

// Add your custom methods and functionality below.
