// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// inviteRecordDao is the data access object for the table invite_record.
// You can define custom methods on it to extend its functionality as needed.
type inviteRecordDao struct {
	*internal.InviteRecordDao
}

var (
	// InviteRecord is a globally accessible object for table invite_record operations.
	InviteRecord = inviteRecordDao{internal.NewInviteRecordDao()}
)

// Add your custom methods and functionality below.
