// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// logisticsCompanyDao is the data access object for the table logistics_company.
// You can define custom methods on it to extend its functionality as needed.
type logisticsCompanyDao struct {
	*internal.LogisticsCompanyDao
}

var (
	// LogisticsCompany is a globally accessible object for table logistics_company operations.
	LogisticsCompany = logisticsCompanyDao{internal.NewLogisticsCompanyDao()}
)

// Add your custom methods and functionality below.
