// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// notifyTemplateDao is the data access object for the table notify_template.
// You can define custom methods on it to extend its functionality as needed.
type notifyTemplateDao struct {
	*internal.NotifyTemplateDao
}

var (
	// NotifyTemplate is a globally accessible object for table notify_template operations.
	NotifyTemplate = notifyTemplateDao{internal.NewNotifyTemplateDao()}
)

// Add your custom methods and functionality below.
