// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// notifyTaskDao is the data access object for the table notify_task.
// You can define custom methods on it to extend its functionality as needed.
type notifyTaskDao struct {
	*internal.NotifyTaskDao
}

var (
	// NotifyTask is a globally accessible object for table notify_task operations.
	NotifyTask = notifyTaskDao{internal.NewNotifyTaskDao()}
)

// Add your custom methods and functionality below.
