// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// operationFloorDao is the data access object for the table operation_floor.
// You can define custom methods on it to extend its functionality as needed.
type operationFloorDao struct {
	*internal.OperationFloorDao
}

var (
	// OperationFloor is a globally accessible object for table operation_floor operations.
	OperationFloor = operationFloorDao{internal.NewOperationFloorDao()}
)

// Add your custom methods and functionality below.
