// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// operationBannerDao is the data access object for the table operation_banner.
// You can define custom methods on it to extend its functionality as needed.
type operationBannerDao struct {
	*internal.OperationBannerDao
}

var (
	// OperationBanner is a globally accessible object for table operation_banner operations.
	OperationBanner = operationBannerDao{internal.NewOperationBannerDao()}
)

// Add your custom methods and functionality below.
