// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// payCallbackLogDao is the data access object for the table pay_callback_log.
// You can define custom methods on it to extend its functionality as needed.
type payCallbackLogDao struct {
	*internal.PayCallbackLogDao
}

var (
	// PayCallbackLog is a globally accessible object for table pay_callback_log operations.
	PayCallbackLog = payCallbackLogDao{internal.NewPayCallbackLogDao()}
)

// Add your custom methods and functionality below.
