// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// pointAccountDao is the data access object for the table point_account.
// You can define custom methods on it to extend its functionality as needed.
type pointAccountDao struct {
	*internal.PointAccountDao
}

var (
	// PointAccount is a globally accessible object for table point_account operations.
	PointAccount = pointAccountDao{internal.NewPointAccountDao()}
)

// Add your custom methods and functionality below.
