// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// pointLogDao is the data access object for the table point_log.
// You can define custom methods on it to extend its functionality as needed.
type pointLogDao struct {
	*internal.PointLogDao
}

var (
	// PointLog is a globally accessible object for table point_log operations.
	PointLog = pointLogDao{internal.NewPointLogDao()}
)

// Add your custom methods and functionality below.
