// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// productSpuDao is the data access object for the table product_spu.
// You can define custom methods on it to extend its functionality as needed.
type productSpuDao struct {
	*internal.ProductSpuDao
}

var (
	// ProductSpu is a globally accessible object for table product_spu operations.
	ProductSpu = productSpuDao{internal.NewProductSpuDao()}
)

// Add your custom methods and functionality below.
