// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// productSkuDao is the data access object for the table product_sku.
// You can define custom methods on it to extend its functionality as needed.
type productSkuDao struct {
	*internal.ProductSkuDao
}

var (
	// ProductSku is a globally accessible object for table product_sku operations.
	ProductSku = productSkuDao{internal.NewProductSkuDao()}
)

// Add your custom methods and functionality below.
