// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// productCategoryDao is the data access object for the table product_category.
// You can define custom methods on it to extend its functionality as needed.
type productCategoryDao struct {
	*internal.ProductCategoryDao
}

var (
	// ProductCategory is a globally accessible object for table product_category operations.
	ProductCategory = productCategoryDao{internal.NewProductCategoryDao()}
)

// Add your custom methods and functionality below.
