// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// productBrandDao is the data access object for the table product_brand.
// You can define custom methods on it to extend its functionality as needed.
type productBrandDao struct {
	*internal.ProductBrandDao
}

var (
	// ProductBrand is a globally accessible object for table product_brand operations.
	ProductBrand = productBrandDao{internal.NewProductBrandDao()}
)

// Add your custom methods and functionality below.
