// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// productReviewDao is the data access object for the table product_review.
// You can define custom methods on it to extend its functionality as needed.
type productReviewDao struct {
	*internal.ProductReviewDao
}

var (
	// ProductReview is a globally accessible object for table product_review operations.
	ProductReview = productReviewDao{internal.NewProductReviewDao()}
)

// Add your custom methods and functionality below.
