// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// promotionActivityScopeDao is the data access object for the table promotion_activity_scope.
// You can define custom methods on it to extend its functionality as needed.
type promotionActivityScopeDao struct {
	*internal.PromotionActivityScopeDao
}

var (
	// PromotionActivityScope is a globally accessible object for table promotion_activity_scope operations.
	PromotionActivityScope = promotionActivityScopeDao{internal.NewPromotionActivityScopeDao()}
)

// Add your custom methods and functionality below.
