// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// promotionActivityLadderDao is the data access object for the table promotion_activity_ladder.
// You can define custom methods on it to extend its functionality as needed.
type promotionActivityLadderDao struct {
	*internal.PromotionActivityLadderDao
}

var (
	// PromotionActivityLadder is a globally accessible object for table promotion_activity_ladder operations.
	PromotionActivityLadder = promotionActivityLadderDao{internal.NewPromotionActivityLadderDao()}
)

// Add your custom methods and functionality below.
