// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// promotionActivityDao is the data access object for the table promotion_activity.
// You can define custom methods on it to extend its functionality as needed.
type promotionActivityDao struct {
	*internal.PromotionActivityDao
}

var (
	// PromotionActivity is a globally accessible object for table promotion_activity operations.
	PromotionActivity = promotionActivityDao{internal.NewPromotionActivityDao()}
)

// Add your custom methods and functionality below.
