// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// riskRecordDao is the data access object for the table risk_record.
// You can define custom methods on it to extend its functionality as needed.
type riskRecordDao struct {
	*internal.RiskRecordDao
}

var (
	// RiskRecord is a globally accessible object for table risk_record operations.
	RiskRecord = riskRecordDao{internal.NewRiskRecordDao()}
)

// Add your custom methods and functionality below.
