// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// riskRuleDao is the data access object for the table risk_rule.
// You can define custom methods on it to extend its functionality as needed.
type riskRuleDao struct {
	*internal.RiskRuleDao
}

var (
	// RiskRule is a globally accessible object for table risk_rule operations.
	RiskRule = riskRuleDao{internal.NewRiskRuleDao()}
)

// Add your custom methods and functionality below.
