// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// shareRecordDao is the data access object for the table share_record.
// You can define custom methods on it to extend its functionality as needed.
type shareRecordDao struct {
	*internal.ShareRecordDao
}

var (
	// ShareRecord is a globally accessible object for table share_record operations.
	ShareRecord = shareRecordDao{internal.NewShareRecordDao()}
)

// Add your custom methods and functionality below.
