// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// storeDao is the data access object for the table store.
// You can define custom methods on it to extend its functionality as needed.
type storeDao struct {
	*internal.StoreDao
}

var (
	// Store is a globally accessible object for table store operations.
	Store = storeDao{internal.NewStoreDao()}
)

// Add your custom methods and functionality below.
