// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// tradeOrderLogDao is the data access object for the table trade_order_log.
// You can define custom methods on it to extend its functionality as needed.
type tradeOrderLogDao struct {
	*internal.TradeOrderLogDao
}

var (
	// TradeOrderLog is a globally accessible object for table trade_order_log operations.
	TradeOrderLog = tradeOrderLogDao{internal.NewTradeOrderLogDao()}
)

// Add your custom methods and functionality below.
