// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// tradeOrderItemDao is the data access object for the table trade_order_item.
// You can define custom methods on it to extend its functionality as needed.
type tradeOrderItemDao struct {
	*internal.TradeOrderItemDao
}

var (
	// TradeOrderItem is a globally accessible object for table trade_order_item operations.
	TradeOrderItem = tradeOrderItemDao{internal.NewTradeOrderItemDao()}
)

// Add your custom methods and functionality below.
