// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// tradeOrderDao is the data access object for the table trade_order.
// You can define custom methods on it to extend its functionality as needed.
type tradeOrderDao struct {
	*internal.TradeOrderDao
}

var (
	// TradeOrder is a globally accessible object for table trade_order operations.
	TradeOrder = tradeOrderDao{internal.NewTradeOrderDao()}
)

// Add your custom methods and functionality below.
