// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// userNotifyPreferenceDao is the data access object for the table user_notify_preference.
// You can define custom methods on it to extend its functionality as needed.
type userNotifyPreferenceDao struct {
	*internal.UserNotifyPreferenceDao
}

var (
	// UserNotifyPreference is a globally accessible object for table user_notify_preference operations.
	UserNotifyPreference = userNotifyPreferenceDao{internal.NewUserNotifyPreferenceDao()}
)

// Add your custom methods and functionality below.
