// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// userLevelRuleDao is the data access object for the table user_level_rule.
// You can define custom methods on it to extend its functionality as needed.
type userLevelRuleDao struct {
	*internal.UserLevelRuleDao
}

var (
	// UserLevelRule is a globally accessible object for table user_level_rule operations.
	UserLevelRule = userLevelRuleDao{internal.NewUserLevelRuleDao()}
)

// Add your custom methods and functionality below.
