// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// userFavoriteDao is the data access object for the table user_favorite.
// You can define custom methods on it to extend its functionality as needed.
type userFavoriteDao struct {
	*internal.UserFavoriteDao
}

var (
	// UserFavorite is a globally accessible object for table user_favorite operations.
	UserFavorite = userFavoriteDao{internal.NewUserFavoriteDao()}
)

// Add your custom methods and functionality below.
