// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// userRelationDao is the data access object for the table user_relation.
// You can define custom methods on it to extend its functionality as needed.
type userRelationDao struct {
	*internal.UserRelationDao
}

var (
	// UserRelation is a globally accessible object for table user_relation operations.
	UserRelation = userRelationDao{internal.NewUserRelationDao()}
)

// Add your custom methods and functionality below.
