// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// userFootprintDao is the data access object for the table user_footprint.
// You can define custom methods on it to extend its functionality as needed.
type userFootprintDao struct {
	*internal.UserFootprintDao
}

var (
	// UserFootprint is a globally accessible object for table user_footprint operations.
	UserFootprint = userFootprintDao{internal.NewUserFootprintDao()}
)

// Add your custom methods and functionality below.
