// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// userAccountDao is the data access object for the table user_account.
// You can define custom methods on it to extend its functionality as needed.
type userAccountDao struct {
	*internal.UserAccountDao
}

var (
	// UserAccount is a globally accessible object for table user_account operations.
	UserAccount = userAccountDao{internal.NewUserAccountDao()}
)

// Add your custom methods and functionality below.
