// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// userCouponDao is the data access object for the table user_coupon.
// You can define custom methods on it to extend its functionality as needed.
type userCouponDao struct {
	*internal.UserCouponDao
}

var (
	// UserCoupon is a globally accessible object for table user_coupon operations.
	UserCoupon = userCouponDao{internal.NewUserCouponDao()}
)

// Add your custom methods and functionality below.
