// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ecboot/internal/dao/internal"
)

// withdrawOrderDao is the data access object for the table withdraw_order.
// You can define custom methods on it to extend its functionality as needed.
type withdrawOrderDao struct {
	*internal.WithdrawOrderDao
}

var (
	// WithdrawOrder is a globally accessible object for table withdraw_order operations.
	WithdrawOrder = withdrawOrderDao{internal.NewWithdrawOrderDao()}
)

// Add your custom methods and functionality below.
